# Print debug information to console
debug = false
# Do not warn for links which redirect to the given URL
do-not-warn-for-redirect-to = ["*reports.risczero.com*"]
# Do not check web links
offline = false
# Check the exact file extension when searching for a file
match-file-extension = true
# List of files and directories which will be ignored
ignore-path = ["node_modules", "html-slides", "html-book"]
# List of links which will be ignored
ignore-links = [
  # Internal
  "{{filePath}}",
  "https://github.com/*/edit*",
  "*workshop.md",
  "*workshop.html",
  "*presentation.md",
  "*presentation.html",
  "*materials.md",
  "*materials.html",
  "*slides.md",
  "*slides.html",
  # External
  "*twitter.com*",
  "*support.giphy.com*",
]
# List of markup types which shall be checked
markup-types = ["Markdown", "Html"]
# Wait time in milliseconds between http request to the same host
# Consider use only if getting `429 - Too Many Requests`
throttle = 0
# Path to the root folder used to resolve all relative paths
root-dir = "./content/"
