[book]
title = "Nuke 🌄 's Book"
authors = ["Nuke-Web3"]
description = "The materials used in Nuke 🌄 's talks and workshops"
language = "en"
multilingual = false
src = "content"

[build]
build-dir = "html-book"
create-missing = false # opt out of helper to create missing stub files, we want to fail if the SUMMARY is incorrect.

[rust]
edition = "2021"

[output.html]
site-url = "/book/" # needed for gh-pages, MUST match repo name on github!
git-repository-url = "https://github.com/nuke-web3/book"
edit-url-template = "https://github.com/nuke-web3/book/edit/main/{path}"
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
fold.enable = true # Sidebar collapses automatically
print.enable = false # disclude support for printable output (slides are mangled)

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
