name: Checks
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/dprint # TODO add more paths here for various checkers
        key: ${{ runner.os }}-${{ hashFiles('**/*dprint.json') }}

    - name: Format Check (dprint)
      uses: dprint/check@v2.2
      with:
        config-path: .dprint.json

    - name: Markup Link Checker (mlc)
      uses: becheran/mlc@v0.17.1

    - name: Check for image issues (orphans and broken links)
      run: ${PWD}/tools/scripts/orphan-image-scan.sh content/
